<?php

namespace UrgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertTypeRepository extends EntityRepository
{
}
