<?php

namespace UrgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Alert_TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Alert_TypeRepository extends EntityRepository
{
}
