<?php

namespace UrgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GravityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GravityRepository extends EntityRepository
{
}
