<?php

namespace UrgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicUserRepository extends EntityRepository
{
}
