<?php

namespace UrgenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeverityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeverityRepository extends EntityRepository
{
}
