urgence_homepage:
    path:     /
    defaults: { _controller: UrgenceBundle:Default:index }
    
urgence_alertsecours:
    path:     /alerter-secours
    defaults: { _controller: UrgenceBundle:Form:index }
    
urgence_voiralertes:
    path:     /voir-alertes
    defaults: { _controller: UrgenceBundle:Alert:voiralertes }

urgence_testInsert:
    path:     /form/insert
    defaults: { _controller: UrgenceBundle:Form:insert }
